### ISSUE TITLE
I encountered some errors while running on M1.

### ISSUE THREAD

**Issue by ZhengHui-Z** [ionet-official/io_launch_binaries#16]
As the title suggests, I encountered some errors while running on M1. Since it's a binary file, I can't view the source code and resolve the issues on my own. I need the administrator's assistance.

The errors are as follows:
```plaintext
Traceback (most recent call last):
  File "launch_script_mac_n.py", line 240, in <module>
  File "launch_script_mac_n.py", line 139, in main
  File "launch_script_mac_n.py", line 121, in load_cache
  File "json/__init__.py", line 293, in load
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 183)
[3851] Failed to execute script 'launch_script_mac_n' due to unhandled exception!
```

**Comment by ilkhom19** [comment]
please update the binaries
