### ISSUE TITLE
Not working on M2 Chip

### ISSUE THREAD

**Issue by suathh** [ionet-official/io_launch_binaries#9]
When I try to run 

launch_binary_mac

I get this error.

Traceback (most recent call last):
  File "launch_script_mac_n.py", line 240, in <module>
  File "launch_script_mac_n.py", line 148, in main
  File "launch_script_mac_n.py", line 32, in check_docker
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
[17791] Failed to execute script 'launch_script_mac_n' due to unhandled exception!

**Comment by JimCurryWang** [comment]
did you install your docker before the run?

**Comment by smiraldr** [comment]
@suathh please install mac silicon version (arm) docker and try again.

**Comment by ilkhom19** [comment]
please update the binaries
